- hosts: localhost
  tags: terraform-secrets

  tasks:
    - name: Create terraform secrets
      ansible.builtin.template:
        src: templates/secrets.auto.tfvars.j2
        dest: ../terraform/secrets.auto.tfvars
        mode: "0644"

    - name: Create terraform .env file
      ansible.builtin.template:
        src: templates/terraform.env.j2
        dest: ../terraform/.env
        mode: "0644"

- hosts: webservers
  roles:
    - role: geerlingguy.pip
      tags: setup

    - role: geerlingguy.docker
      tags: setup

    - role: datadog.dd.agent
      tags: monitoring

  pre_tasks:
    - name: Perform full system upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      tags: setup

  tasks:
    - name: Create Redmine env file
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: /tmp/redmine.env
        mode: '0644'
      tags:
        - deploy

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        state: started
        restart_policy: always
        ports:
          - "{{ redmine_port }}:{{ redmine_port }}"
        env_file: /tmp/redmine.env
      tags:
        - deploy